openapi: 3.0.0
info:
  title: 'oddscp.com: LIVE Odds HTTP API'
  description: |-
    API для получения букмекерских вилок и информации о LIVE спортивных
    событиях
  version: '0.1'
servers:
  - url: 'http://212.109.216.193:7777'
tags:
  - name: Sport
    x-displayName: Sport
    description: '<SchemaDefinition schemaRef="#/components/schemas/Sport" />'
  - name: Bookmaker
    x-displayName: Bookmaker
    description: '<SchemaDefinition schemaRef="#/components/schemas/Bookmaker" />'
  - name: BetType
    x-displayName: BetType
    description: '<SchemaDefinition schemaRef="#/components/schemas/BetType" />'
  - name: Fork
    x-displayName: Fork
    description: '<SchemaDefinition schemaRef="#/components/schemas/Fork" />'
  - name: BetbotFork
    x-displayName: BetbotFork
    description: '<SchemaDefinition schemaRef="#/components/schemas/BetbotFork" />'
  - name: ForkHistory
    x-displayName: ForkHistory
    description: |
      Одно изменение рынка (массив)
      <SchemaDefinition schemaRef="#/components/schemas/ForkHistory" />
  - name: BkEvent
    x-displayName: BkEvent
    description: |
      Событие на определенном букмекере
      <SchemaDefinition schemaRef="#/components/schemas/BkEvent" />
  - name: GlobalEvent
    x-displayName: GlobalEvent
    description: |
      Группа событий с разных букмекеров, объединенные в одно
      <SchemaDefinition schemaRef="#/components/schemas/GlobalEvent" />
  - name: Market
    x-displayName: Market
    description: '<SchemaDefinition schemaRef="#/components/schemas/Market" />'
  - name: MarketWithHistory
    x-displayName: MarketWithHistory
    description: '<SchemaDefinition schemaRef="#/components/schemas/MarketWithHistory" />'
  - name: MarketHistory
    x-displayName: MarketHistory
    description: |
      Одно изменения рынка на определенном букмекере
      <SchemaDefinition schemaRef="#/components/schemas/MarketHistory" />
x-tagGroups:
  - name: Основные
    tags:
      - LIVE-Вилки
      - LIVE-События
      - Вспомогательное
  - name: Модели
    tags:
      - Sport
      - Bookmaker
      - BetType
      - Fork
      - BetbotFork
      - ForkHistory
      - BkEvent
      - GlobalEvent
      - Market
      - MarketWithHistory
      - MarketHistory
paths:
  /api/sports:
    get:
      tags:
        - Вспомогательное
      summary: Виды спорта
      description: Возвращает список доступных видов спорта с описанием
      operationId: getSports
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sport'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /api/bookmakers:
    get:
      tags:
        - Вспомогательное
      summary: Букмекеры
      description: |-
        Возвращает список доступных букмекеров с описанием. В список войдут
        только те букмекеры, которые были запрошены/оплачены в Вашем тарифе.
      operationId: getBookmakers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bookmaker'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /api/forks:
    get:
      tags:
        - LIVE-Вилки
      description: Возвращает список LIVE-вилок по заданным параметрам
      summary: Получить список LIVE-вилок
      operationId: getForks
      parameters:
        - name: format
          description: Формат вывода данных
          in: query
          schema:
            type: string
            default: null
            enum:
              - null
              - betbot
        - name: bet_types
          description: Тип ставок в вилке
          in: query
          style: form
          explode: false
          example: 'HALF_WIN,WIN'
          schema:
            type: array
            items:
              $ref: '#/components/schemas/BetType'
        - name: sport
          description: Спорт
          in: query
          style: form
          explode: false
          example: 'tennis,soccer'
          schema:
            type: array
            items:
              type: string
        - name: event_id
          description: Получение вилок только по указанному id события
          in: query
          schema:
            type: integer
          example: 181993
        - name: bk2_name
          description: 'Список букмекеров, участвующих в вилке'
          in: query
          required: true
          style: form
          explode: false
          example: 'fonbet,olimp,bet365'
          schema:
            type: array
            items:
              type: string
        - name: bk_name
          description: 'Букмекер, который обязательно должен участвовать в вилке'
          in: query
          example: fonbet
          schema:
            type: string
        - name: min_cf
          description: Минимальный коэффициент
          in: query
          example: 1.1
          schema:
            type: number
        - name: max_cf
          description: Максимальный коэффициент
          in: query
          example: 3.5
          schema:
            type: number
        - name: min_fi
          description: Минимальный % вилки
          in: query
          example: -1
          schema:
            type: number
        - name: max_fi
          description: Максимальный % вилки
          in: query
          example: 10
          schema:
            type: number
        - name: is_middles
          description: |-
            Коридоры в выдачи. -1 - без коридоров. 0 - вилки и коридоры.
            1 - только коридоры
          in: query
          schema:
            type: integer
            default: 0
            enum:
              - -1
              - 0
              - 1
        - name: alive_sec
          description: Минимальное время существования вилки
          in: query
          schema:
            type: number
            default: 0
      responses:
        '200':
          description: Возвращает массив Fork или BetbotFork в зависимости от параметра
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: '#/components/schemas/Fork'
                  - type: array
                    items:
                      $ref: '#/components/schemas/BetbotFork'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          $ref: '#/components/responses/MissingParameterError'
  /api/fork:
    get:
      tags:
        - LIVE-Вилки
      summary: Получить детали вилки
      description: |-
        Запрос для получения подробных деталей по отдельной вилке (по её
        ключу)
      operationId: getFork
      parameters:
        - name: key
          description: Идентификатор вилки
          required: true
          in: query
          example: 182128_6788852932bc1c34fc3f901f1dff25e2
          schema:
            type: string
      responses:
        '200':
          description: Возвращает Fork
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fork'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Вилка не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          $ref: '#/components/responses/MissingParameterError'
  /api/bk_events:
    get:
      tags:
        - LIVE-События
      summary: Получить список всех активных событий
      description: Запрос для получения всех активных событий
      operationId: getBkEvents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BkEvent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /api/bk_event:
    get:
      tags:
        - LIVE-События
      summary: Поиск события на определенном букмекере
      description: Запрос для поиска определенного события по id или названию
      operationId: getBkEvent
      parameters:
        - name: name
          description: Название события
          in: query
          schema:
            type: string
          example: Manchester United vs Chelsea
        - name: id
          description: id события
          in: query
          schema:
            type: string
          example: '1143492113045229'
        - name: full
          description: Включает markets в ответ
          in: query
          schema:
            type: boolean
            default: true
        - name: bet
          description: |-
            Оставляет в markets только указанную ставку. Работает только
            при full=true
          in: query
          schema:
            type: string
          example: WIN__P1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BkEvent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Событие не найдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          $ref: '#/components/responses/MissingParameterError'
  /api/event:
    get:
      tags:
        - LIVE-События
      summary: Получить группу связанных событий
      description: |-
        Запрос для получения всех событий с разных букмекеров, которые
        объединены в одну группу
      operationId: getEvent
      parameters:
        - name: token
          required: true
          description: Ключ пользователя
          in: query
          schema:
            type: string
          example: dasfhd71316t3sdf03271g2mfdsoe712
        - name: id
          required: true
          description: id события
          in: query
          schema:
            type: integer
          example: 182220
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalEvent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Событие не найдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          $ref: '#/components/responses/MissingParameterError'
  /api/market:
    get:
      tags:
        - LIVE-События
      summary: Поиск определенного рынка на букмекере
      description: Запрос для поиска определенного рынка на заданном букмекере
      operationId: getBkMarket
      parameters:
        - name: bk_event_id
          required: true
          description: id события
          in: query
          schema:
            type: string
          example: 6V84001788C1A_1_1
        - name: bet
          required: true
          description: Название ставки
          in: query
          schema:
            type: string
          example: WIN__P1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketWithHistory'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Рынок не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          $ref: '#/components/responses/MissingParameterError'
components:
  schemas:
    Fork:
      type: object
      required:
        - fi
        - ow
        - is_middles
        - alive_sec
        - bk1_name
        - bk2_name
        - bk1_event_id
        - bk2_event_id
        - bk1_game
        - bk2_game
        - bk1_bet
        - bk2_bet
        - bk1_alt_bet
        - bk2_alt_bet
        - bk1_cf
        - bk2_cf
        - bk1_href
        - bk2_href
        - bk1_league
        - bk2_league
        - bk1_score
        - bk2_score
        - bk1_blocked
        - bk2_blocked
        - bk1_swapped
        - bk2_swapped
        - bk1_bet_type
        - bk2_bet_type
        - bet_type
        - sport
        - blocked
        - bk1_margin
        - bk2_margin
        - history
        - fork_key
        - event_id
      properties:
        fork_key:
          type: string
          description: Ключ вилки
        event_id:
          type: number
          description: Идентификатор группы событий
        fi:
          type: number
          description: fork_income. % вилки
        ow:
          type: number
          description: fi * 2 + bk1_margin + bk2_margin
        is_middles:
          type: integer
          description: 0 - обычная вилка. 1 - коридор
        alive_sec:
          type: number
          description: Время жизни вилки в секундах
        bk1_name:
          type: string
          description: Идентификатор первой БК (БК-1)
          example: fonbet
        bk2_name:
          type: string
          description: Идентификатор второй БК (БК-2)
          example: fonbet
        bk1_bet_type:
          description: Тип ставки на БК-1
          $ref: '#/components/schemas/BetType'
        bk2_bet_type:
          description: Тип ставки на БК-2
          $ref: '#/components/schemas/BetType'
        bet_type:
          description: |-
            Общий тип ставок в вилке. Если bk1_bet_type = bk2_bet_type,
            то bet_type = bk1_bet_type, иначе MIX
        sport:
          type: string
          description: Вид спорта
          example: tennis
        blocked:
          type: boolean
          description: Индикатор блокировки одной из ставок
        bk1_game:
          type: string
          description: Название события на БК-1
        bk2_game:
          type: string
          description: Название события на БК-2
        bk1_bet:
          type: string
          description: Ставка на БК-1
        bk2_bet:
          type: string
          description: Ставка на БК-2
        bk1_alt_bet:
          type: string
          nullable: true
          description: Альтернативная ставка на БК-1
        bk2_alt_bet:
          type: string
          nullable: true
          description: Альтернативная ставка на БК-2
        bk1_cf:
          type: number
          description: Коэффициент на БК-1
        bk2_cf:
          type: number
          description: Коэффициент на БК-2
        bk1_event_id:
          type: string
          description: Идентификатор события на БК-1
        bk2_event_id:
          type: string
          description: Идентификатор события на БК-2
        bk1_href:
          type: string
          description: Ссылка на событие на БК-1
        bk2_href:
          type: string
          description: Ссылка на событие на БК-2
        bk1_league:
          type: string
          description: Название лиги на БК-1
        bk2_league:
          type: string
          description: Название лиги на БК-2
        bk1_score:
          type: string
          description: Текущий счёт на БК-1
        bk2_score:
          type: string
          description: Текущий счёт на БК-2
        bk1_margin:
          type: number
          nullable: true
          description: Маржа на БК-1
        bk2_margin:
          type: number
          nullable: true
          description: Маржа на БК-2
        history:
          type: array
          description: Последние 10 изменений коэффициентов
          items:
            $ref: '#/components/schemas/ForkHistory'
        bk1_blocked:
          type: boolean
          description: Индикатор блокировки рынка на БК-1
        bk2_blocked:
          type: boolean
          description: Индикатор блокировки рынка на БК-1
        bk1_swapped:
          type: boolean
          description: |-
            Индикатор того, чтобы событие перевернуто относительно остальных
            событий в группе (GlobalEvent) на БК-1. Например на одном букмекере событие
            называется "Liverpool vs Chelsea", а на всех других - "Chelsea vs Liverpool".
        bk2_swapped:
          type: boolean
          description: |-
            Индикатор того, чтобы событие перевернуто относительно остальных
            событий в группе (GlobalEvent) на БК-2
      example:
        alive_sec: 35.0165781975
        bet_type: HANDICAP
        bk1_alt_bet: null
        bk1_bet: HANDICAP__P1(-1.5)
        bk1_bet_type: HANDICAP
        bk1_blocked: false
        bk1_cf: 1.88
        bk1_event_id: '17641387'
        bk1_game: Игнатьев Д vs Журба Н
        bk1_href: 'https://www.fonbet.ru/#!/live/table-tennis/37716/17641387'
        bk1_league: Лига Про. Москва
        bk1_margin: 8.1365443068
        bk1_name: fonbet
        bk1_score: '0:0 (0*:0)'
        bk1_swapped: 0
        bk2_alt_bet: null
        bk2_bet: HANDICAP__P2(1.5)
        bk2_bet_type: HANDICAP
        bk2_blocked: false
        bk2_cf: 2.24
        bk2_event_id: '6409850'
        bk2_game: Ignatiev Dmitry vs Zhurba N.
        bk2_href: 'https://betcityru.com/en/live/table-tennis/105065/6409850'
        bk2_league: Table Tennis. Russia. League Pro. Men.
        bk2_margin: 7.1428571429
        bk2_name: betcity
        bk2_score: '0:0 (0:0)'
        bk2_swapped: 0
        blocked: false
        event_id: 187915
        fi: 2.17
        fork_key: 187915_cc9098a4ad20410512848d0fa32e6631
        history:
          - |-
            - 1573193419.991
            - 2.17
            - 1.88
            - 2.24
            - 0:0 (0:0)
            - 0:0 (0:0)
            - false
            - false
        is_middles: false
        ow: 19.6194014496
        sport: table-tennis
    BetbotFork:
      type: object
      required:
        - fork_id
        - event_id
        - income
        - ow_income
        - is_middles
        - BK1_name
        - BK2_name
        - BK1_bet_type
        - BK2_bet_type
        - bet_type
        - sport
        - BK1_game
        - BK2_game
        - BK1_bet
        - BK2_bet
        - BK1_alt_bet
        - BK2_alt_bet
        - BK1_cf
        - BK2_cf
        - BK1_event_id
        - BK2_event_id
        - BK1_href
        - BK2_href
        - BK1_league
        - BK2_league
        - BK1_score
        - BK2_score
        - BK1_swapped
        - BK2_swapped
      properties:
        fork_id:
          type: string
          description: Ключ вилки (fork_key)
        event_id:
          type: number
          description: Идентификатор группы событий
        income:
          type: number
          description: '% вилки (fi)'
        ow_income:
          type: number
          description: fi * 2 + bk1_margin + bk2_margin (ow)
        is_middles:
          type: boolean
          description: false - обычная вилка. true - коридор
        BK1_name:
          type: string
          description: Идентификатор первой БК (БК-1)
          example: fonbet
        BK2_name:
          type: string
          description: Идентификатор второй БК (БК-2)
          example: fonbet
        BK1_bet_type:
          description: Тип ставки на БК-1
          $ref: '#/components/schemas/BetType'
        BK2_bet_type:
          description: Тип ставки на БК-2
          $ref: '#/components/schemas/BetType'
        bet_type:
          description: |-
            Общий тип ставок в вилке. Если bk1_bet_type = bk2_bet_type,
            то bet_type = bk1_bet_type, иначе MIX
        sport:
          type: string
          description: Вид спорта
          example: tennis
        BK1_game:
          type: string
          description: Название события на БК-1
        BK2_game:
          type: string
          description: Название события на БК-2
        BK1_bet:
          type: string
          description: Ставка на БК-1
        BK2_bet:
          type: string
          description: Ставка на БК-2
        BK1_alt_bet:
          type: string
          nullable: true
          description: Альтернативная ставка на БК-1
        BK2_alt_bet:
          type: string
          nullable: true
          description: Альтернативная ставка на БК-2
        BK1_cf:
          type: number
          description: Коэффициент на БК-1
        BK2_cf:
          type: number
          description: Коэффициент на БК-2
        BK1_event_id:
          type: string
          description: Идентификатор события на БК-1
        BK2_event_id:
          type: string
          description: Идентификатор события на БК-2
        BK1_href:
          type: string
          description: Ссылка на событие на БК-1
        BK2_href:
          type: string
          description: Ссылка на событие на БК-2
        BK1_league:
          type: string
          description: Название лиги на БК-1
        BK2_league:
          type: string
          description: Название лиги на БК-2
        BK1_score:
          type: string
          description: Текущий счёт на БК-1
        BK2_score:
          type: string
          description: Текущий счёт на БК-2
        BK1_swapped:
          type: number
          description: |-
            Индикатор того, чтобы событие перевернуто относительно остальных
            событий в группе (GlobalEvent) на БК-1. Например на одном букмекере событие
            называется "Liverpool vs Chelsea", а на всех других - "Chelsea vs Liverpool".
        BK2_swapped:
          type: number
          description: |-
            Индикатор того, чтобы событие перевернуто относительно остальных
            событий в группе (GlobalEvent) на БК-2
      example:
        BK1_alt_bet: null
        BK1_bet: HANDICAP__P1(0.5)
        BK1_bet_type: MIX
        BK1_cf: 1.714
        BK1_event_id: '1060523833'
        BK1_game: Guria Lanchkhuti vs Baia Zugdidi
        BK1_href: 'https://beta.pinnacle.com/ru/Sports/29/Leagues/201857/Events/1060523833'
        BK1_league: Georgia - Erovnuli Liga 2
        BK1_name: pinnacle
        BK1_score: '0:0'
        BK1_swapped: 0
        BK2_alt_bet: null
        BK2_bet: WIN__P2
        BK2_bet_type: MIX
        BK2_cf: 3.6
        BK2_event_id: 6V83782549C1A_1_1
        BK2_game: Guria Lanchkhuti vs FC Zugdidi
        BK2_href: 'https://www.bet365.com'
        BK2_league: Georgia Erovnuli Liga 2
        BK2_name: bet365
        BK2_score: '0:0'
        BK2_swapped: 0
        bet_type: MIX
        event_id: 188144
        fork_id: 188144_40c0ebb95a2bb632c685e259e463f84a
        income: 13.88
        is_middles: false
        ow_income: -100
        sport: soccer
    Sport:
      type: object
      required:
        - name
        - display_name
      properties:
        name:
          type: string
          description: Используется для запросов
        display_name:
          type: string
          description: Название на русском
      example:
        name: tennis
        display_name: Теннис
    Bookmaker:
      type: object
      required:
        - id
        - name
        - display_name
      properties:
        id:
          type: string
          description: Краткое обозначение букмекера
        name:
          type: string
          description: Используется для запросов
        display_name:
          type: string
          description: Название на русском
      example:
        id: FON
        name: fonbet
        display_name: Фонбет
    BetType:
      type: string
      enum:
        - MIX
        - WIN
        - SET_WIN
        - HALF_WIN
        - WIN_CORNERS
        - HALF_WIN_CORNERS
        - ASIAN_TOTALS
        - SET_ASIAN_TOTALS
        - HALF_ASIAN_TOTALS
        - ASIAN_TOTALS_CORNERS
        - HALF_ASIAN_TOTALS_CORNERS
        - TOTALS
        - SET_TOTALS
        - HALF_TOTALS
        - TOTALS_CORNERS
        - HALF_TOTALS_CORNERS
        - TOTALS3W_CORNERS
        - HALF_TOTALS3W_CORNERS
        - TEAM_TOTALS
        - SET_TEAM_TOTALS
        - HALF_TEAM_TOTALS
        - TEAM_TOTALS_CORNERS
        - HALF_TEAM_TOTALS_CORNERS
        - HANDICAP
        - SET_HANDICAP
        - HALF_HANDICAP
        - HANDICAP_CORNERS
        - HALF_HANDICAP_CORNERS
        - ALL_TEAMS_GOALS
        - SET_ALL_TEAMS_GOALS
        - HALF_ALL_TEAMS_GOALS
        - TEAM_GOALS
        - SET_TEAM_GOALS
        - HALF_TEAM_GOALS
        - GAME_WIN
    ForkHistory:
      type: object
      properties:
        - type: number
          description: timestamp изменения
        - type: number
          description: '% вилки'
        - type: number
          description: cf1
        - type: number
          description: cf2
        - type: string
          description: score1
        - type: string
          description: score2
        - type: boolean
          description: blocked1
        - type: boolean
          description: blocked2
      example:
        - 15731923160.29
        - 5.7
        - 2.2
        - 2.1
        - '0:1'
        - '0:1 13:55'
        - false
        - false
    MarketHistory:
      type: object
      properties:
        - type: number
          description: timestamp изменения
        - type: number
          description: cf
        - type: boolean
          description: blocked
      example:
        - 15731923160.29
        - 2.2
        - false
    BkEvent:
      type: object
      required:
        - bk_name
        - event_id
        - bk_event_id
        - event_name
        - direct_link
        - league_name
        - score
        - sport
        - swapped
      properties:
        bk_name:
          type: string
          example: fonbet
          description: Идентификатор букмекера
        event_id:
          type: integer
          description: Идентификатор группы событий
        bk_event_id:
          type: string
          description: Идентификатор события на букмекере
        event_name:
          type: string
          description: Полное название события
        direct_link:
          type: string
          description: Ссылка на событие на БК
        league_name:
          type: string
          description: Название лиги/соревнования
        score:
          type: string
          description: Текущий счёт
        sport:
          type: string
          example: tennis
          description: Вид спорта
        swapped:
          type: boolean
          description: |-
            Индикатор того, чтобы событие перевернуто относительно остальных
            событий в группе (GlobalEvent). Например на одном букмекере событие называется
            "Liverpool vs Chelsea", а на всех других - "Chelsea vs Liverpool".
        markets:
          type: array
          description: Массив доступных ставок
          items:
            $ref: '#/components/schemas/Market'
      example:
        bk_event_id: '213518329'
        bk_name: 1xbet
        direct_link: 'https://1xbet.com/live/Football/105583-Japan-Regional-League/213518329-Iwaki-Hokkaido-Tokachi'
        event_id: 187882
        event_name: Иваки vs Хоккайдо Токачи
        invalidated: null
        league_name: Чемпионат Японии. Региональная лига
        score: '2:1 (2:0) 92:01'
        sport: soccer
        swapped: 0
        markets:
          - added_at: 1573187254.9918098
            alt_bet: null
            bet: WIN__P1
            bet_type: WIN
            bk_event_id: '213518329'
            bk_name: 1xbet
            blocked: true
            cf: 1.01
            direct_link: null
            updated_at: 1573193923.8590028
    Market:
      type: object
      required:
        - bk_event_id
        - bk_name
        - bet
        - alt_bet
        - cf
        - direct_link
        - blocked
        - bet_type
        - added_at
        - updated_at
      properties:
        bk_event_id:
          type: string
          description: Идентификатор события на букмекере
        bk_name:
          type: string
          example: fonbet
          description: Идентификатор букмекера
        bet:
          type: string
          description: Название ставки
        alt_bet:
          type: string
          nullable: true
          description: Альтернативное название ставки
        cf:
          type: number
          description: Коэффициент
        direct_link:
          type: string
          description: Ссылка на событие
        blocked:
          type: boolean
          description: Индикатор блокировки ставки (ставка недоступна на самой БК)
        bet_type:
          description: Тип ставки
          $ref: '#/components/schemas/BetType'
        added_at:
          type: number
          description: Метка времени последнего появления ставки
        updated_at:
          type: number
          description: Метка времени последнего обновления ставки
      example:
        added_at: 1573187254.9918098
        alt_bet: null
        bet: WIN__P1
        bet_type: WIN
        bk_event_id: '213518329'
        bk_name: 1xbet
        blocked: false
        cf: 1.02
        direct_link: null
        updated_at: 1573193575.0244918
    MarketWithHistory:
      allOf:
        - $ref: '#/components/schemas/Market'
        - type: object
          required:
            - history
          properties:
            history:
              type: array
              description: История изменения рынка
              items:
                $ref: '#/components/schemas/MarketHistory'
    GlobalEvent:
      type: object
      required:
        - event_id
        - events
      properties:
        event_id:
          type: number
          description: Идентификатор группы событий
        events:
          type: array
          description: Массив событий в группе
          items:
            $ref: '#/components/schemas/BkEvent'
      example:
        event_id: 187915
        events:
          - bk_event_id: '45896880'
            bk_name: parimatch
            direct_link: 'https://www.parimatch.com/bet.html?pfrom=live&hl=45896880'
            event_id: 187882
            event_name: Иваки СК vs Хоккайдо Токати
            invalidated: null
            league_name: Футбол. Япония. Региональные лиги
            score: '2:1 (2:0 0:1)'
            sport: soccer
            swapped: 0
          - bk_event_id: '213518329'
            bk_name: 1xbet
            direct_link: 'https://1xbet.com/live/Football/105583-Japan-Regional-League/213518329-Iwaki-Hokkaido-Tokachi'
            event_id: 187882
            event_name: Иваки vs Хоккайдо Токачи
            invalidated: null
            league_name: Чемпионат Японии. Региональная лига
            score: '2:1 (2:0) 92:01'
            sport: soccer
            swapped: 0
    Error:
      type: object
      properties:
        error:
          type: string
  securitySchemes:
    URITokenAuth:
      description: |-
        Ключ пользователя передаётся со всеми остальными параметрами в
        Query String. Его можно найти в Личном Кабинете, после оплаты/подключения
        тарифа.
      type: apiKey
      in: query
      name: token
  responses:
    UnauthorizedError:
      description: 'Токен отсутствует, просрочен или не хватает прав'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    MissingParameterError:
      description: Отсутствует указанный параметр
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
security:
  - URITokenAuth: []
